select
    trip_id as trip_key,
    vendor_id as vendor_key,
    rate_code_id as rate_code_key,
    payment_type_id as payment_type_key,
    pickup_location_id as pickup_location_key,
    dropoff_location_id as dropoff_location_key,
    to_number(to_char(pickup_datetime::date, 'YYYYMMDD')) as pickup_date_key,
    to_number(to_char(dropoff_datetime::date, 'YYYYMMDD')) as dropoff_date_key,
    pickup_datetime,
    dropoff_datetime,
    passenger_count,
    trip_distance,
    trip_duration_seconds,
    fare_amount,
    extra_amount,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    total_amount,
    congestion_surcharge,
    airport_fee,
    cbd_congestion_fee,
    store_and_fwd_flag,
    source_period,
    source_file,
    loaded_at
from {{ ref('yellow_taxi_trips') }}
