-- Ejecutar una sola vez en un Worksheet de Snowflake con un rol que pueda
-- crear bases de datos, esquemas, tablas, stages y file formats.
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS LAB_SEMANA_07_DB;

CREATE SCHEMA IF NOT EXISTS LAB_SEMANA_07_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS LAB_SEMANA_07_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS LAB_SEMANA_07_DB.GOLD;

CREATE FILE FORMAT IF NOT EXISTS LAB_SEMANA_07_DB.BRONZE.NYC_TAXI_PARQUET_FORMAT
    TYPE = PARQUET
    USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS LAB_SEMANA_07_DB.BRONZE.NYC_TAXI_STAGE;

CREATE TABLE IF NOT EXISTS LAB_SEMANA_07_DB.BRONZE.YELLOW_TAXI_RAW (
    RAW_RECORD VARIANT NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_PERIOD VARCHAR(7) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS LAB_SEMANA_07_DB.BRONZE.TAXI_ZONE_LOOKUP_RAW (
    LOCATION_ID NUMBER,
    BOROUGH VARCHAR,
    ZONE VARCHAR,
    SERVICE_ZONE VARCHAR,
    SOURCE_FILE VARCHAR NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);

-- Validación rápida del setup.
SHOW SCHEMAS IN DATABASE LAB_SEMANA_07_DB;
SHOW TABLES IN SCHEMA LAB_SEMANA_07_DB.BRONZE;
SHOW STAGES IN SCHEMA LAB_SEMANA_07_DB.BRONZE;
