USE DATABASE LAB_SEMANA_07_DB;

-- Debe devolver un período por archivo cargado y cero duplicados de período.
SELECT
    SOURCE_PERIOD,
    COUNT(*) AS ROW_COUNT,
    MIN(LOADED_AT) AS LOADED_AT
FROM BRONZE.YELLOW_TAXI_RAW
GROUP BY SOURCE_PERIOD
ORDER BY SOURCE_PERIOD;

-- Conteos generales de las tres capas.
SELECT 'BRONZE' AS LAYER, COUNT(*) AS ROW_COUNT FROM BRONZE.YELLOW_TAXI_RAW
UNION ALL
SELECT 'SILVER', COUNT(*) FROM SILVER.YELLOW_TAXI_TRIPS
UNION ALL
SELECT 'GOLD', COUNT(*) FROM GOLD.FCT_TRIPS;

-- La tabla de hechos no debe contener llaves de viaje duplicadas.
SELECT TRIP_KEY, COUNT(*) AS DUPLICATES
FROM GOLD.FCT_TRIPS
GROUP BY TRIP_KEY
HAVING COUNT(*) > 1;

-- Resumen analítico de ejemplo.
SELECT
    D.YEAR,
    D.MONTH,
    COUNT(*) AS TRIPS,
    ROUND(SUM(F.TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(AVG(F.TRIP_DISTANCE), 2) AS AVG_DISTANCE
FROM GOLD.FCT_TRIPS F
JOIN GOLD.DIM_DATE D
  ON F.PICKUP_DATE_KEY = D.DATE_KEY
GROUP BY D.YEAR, D.MONTH
ORDER BY D.YEAR, D.MONTH;
